---
- name: Set-up test webapp
  hosts: webservers
  become: true
  tasks:
  - name: Connection test
    ping:

  - name: install apache
    apt: 
      name: apache2
      state: present

  - name: start apache2
    service:
      name: apache2
      state: started  
