---
- name: add or update password
  hosts: extservers
  remote_user: krvnryssl

  tasks:
  - name: Change user  password
    become: yes
    become_user: root
    user:
      name: "{{ user }}"
      update_password: always
      password: "{{ newpassword|password_hash('sha512') }}"
