---
- name: Install apache2 package
  apt:
        name: apache2
        state: present
          
- name: start apache
  service:
        name: apache2
        state: started
          
- name: Open port for http
  firewalld:
        service: http
        permanent: true
        state: enabled
          
- name: Restart firewalld
  service:
        name: firewalld
        state: reloaded 
