---
- name: kill process sample
  hosts: webservers
  remote_user: krvnryssl

  tasks:
    - name: Get running processes from remote host
      ignore_errors: 'yes'
      shell: "ps -few | grep apache | awk '{print $2}'"
      register: running_process

    - name: Kill running process
      become: true
      ignore_errors: yes
      shell: "kill {{ item }}"
      with_items: "{{ running_process.stdout_lines }}"


