---
- name: Set-up test webapp
  hosts: webservers
  remote_user: svc-test
  tasks:
  - name: Connection test
    ping:

  - name: install apache
    become: true
    apt: 
      name: apache2
      state: present

  - name: start apache2
    service:
      name: apache2
      state: started  
